name: 'Pull request linter action'
description: "Lint your pull request name based on commitlint configuration"
author: 'Julien Karst'
inputs:
  configurationPath:
    description: 'The path for the commitlint configurations'
    required: true
    default: './commitlint.config.js'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'users'
  color: 'blue'
